# Generated by Django 6.0.3 on 2026-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_alter_productsize_size_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', max_length=20),
        ),
    ]
