# Generated by Django 6.0.3 on 2026-03-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cartitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
